networks:
  app_net:

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - app_net
    command: python app.py
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  client:
    build: ./client
    networks:
      - app_net
    command: python client.py
    depends_on:
      server:
        condition: service_healthy